### ISSUE TITLE
Mark all Mojos as ThreadSafe

### ISSUE THREAD

**Issue by SemmelJochen** [mojohaus/native2ascii-maven-plugin#20]
We are trying to use this plugin with a parallel Maven build. But it seems that the threadSafe Annotation is missing in the native2ascii Mojos.

![image](https://github.com/mojohaus/native2ascii-maven-plugin/assets/43446941/ef08f31f-9f5c-4c1b-b991-f4f1d2d0b6f0)

**Comment by dmatej** [comment]
Oh, right on time! I knew I forgot something I wanted to do before the release! :-)
Thanks!

**Comment by SemmelJochen** [comment]
Thank you for the fast reply and fix :)
