### ISSUE TITLE
Using in Windows ends with PatternSyntaxException

### ISSUE THREAD

**Issue by krpata** [mojohaus/native2ascii-maven-plugin#3]
In Windows plugin throws PatternSyntaxException.
Native2AsciiMojoTest.testFile failed.

> Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
> C:\Users\krpata\workspace\cz.aura.isl.mcc.i18n-TRUNK\src\main\resources
>    ^
> 	at java.util.regex.Pattern.error(Pattern.java:1955)
> 	at java.util.regex.Pattern.escape(Pattern.java:2471)
> 	at java.util.regex.Pattern.atom(Pattern.java:2198)
> 	at java.util.regex.Pattern.sequence(Pattern.java:2130)
> 	at java.util.regex.Pattern.expr(Pattern.java:1996)
> 	at java.util.regex.Pattern.compile(Pattern.java:1696)
> 	at java.util.regex.Pattern.<init>(Pattern.java:1351)
> 	at java.util.regex.Pattern.compile(Pattern.java:1028)
> 	at java.lang.String.replaceFirst(String.java:2178)
> 	at org.codehaus.mojo.native2ascii.mojo.Native2AsciiMojo.executeTransformation(Native2AsciiMojo.java:75)
> 	at org.codehaus.mojo.native2ascii.mojo.AbstractNative2AsciiMojo.execute(AbstractNative2AsciiMojo.java:61)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

**Comment by dmatej** [comment]
I have pushed automatic test and fix but I have no Windows machine now to try it. Can you do that, please?
Only make sure to mvn clean install the plugin from this repository and then change the version to 2.0.1-SNAPSHOT in your project.
If it would pass we can initiate next release in one or two weeks.

**Comment by krpata** [comment]
Your repaire is correct, thanks.

**Comment by cgrings** [comment]
Hello guys,
Any idea when the next release will be available with this bug fixed?

**Comment by dmatej** [comment]
Hi, I hope I could make it until the end of january.
